🖕😏🖕
jakearchibald/I-rudely-reject-pull-requests-to-this-repo pull request #49
Opened 2020-10-23 01:52 UTC by rowe-morehouse

🖕😏🖕

2020-12-15 11:53 UTC, Shuunen commented
this repo is cleary un-maintained

2020-12-15 11:55 UTC, Shuunen requested changes
something more classy please

2020-12-15 11:55 UTC, Shuunen commented on README.md
> +<span title="🖕😏🖕"></span>
I would rather go for `<span title="🖕">😏</span>`

2020-12-15 11:56 UTC, Shuunen commented
the guy must be compressing bitmap or svg again, don't blame him I have the same OCD

2020-12-17 10:03 UTC, jakearchibald commented
this didn't even deserve to be rejected in a timely fashion

2020-12-17 10:03 UTC, closed without merging

2020-12-17 10:54 UTC, Shuunen commented
Nooooooo